version: "3"

services:
  nuxt:
    build: .
    container_name: nuxt-container
    restart: always
    ports:
      - "3000:3000"
    command: "yarn start"

  nginx:
    image: nginx:1.17
    container_name: nginx-container
    restart: always
    env_file: .env
    ports:
      - "${DOCKER_APP_PORT}:80"
    volumes:
      - .nginx:/etc/nginx/conf.d
      - "${DOCKER_LOG_PATH}:/var/log/nginx"
      - "${DOCKER_BASIC_AUTH_PASSWORD_FILE}:/etc/nginx/.htpasswd"
    depends_on:
      - nuxt
